# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-11 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0003_abouttextstairs_abouttextstairsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_eventslist', serialize=False, to='cms.CMSPlugin')),
                ('mode', models.CharField(choices=[('1', 'Actual'), ('2', 'Archive')], default='1', max_length=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
