# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-11 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='mode',
            field=models.CharField(choices=[('actual', 'Actual'), ('archive', 'Archive')], default='actual', max_length=1),
        ),
    ]
