# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-11 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0006_auto_20190611_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spacer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_spacer', serialize=False, to='cms.CMSPlugin')),
                ('size', models.PositiveSmallIntegerField(null=True)),
                ('size_mobile', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
