# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-11 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0008_shoptitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTextCylinder',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_shoptextcylinder', serialize=False, to='cms.CMSPlugin')),
                ('text', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
