# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0011_shoptextandframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTextWaves',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_shoptextwaves', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
