# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-12 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_abouttextwithbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttextwithbackground',
            name='image',
            field=models.ImageField(null=True, upload_to='about/plugins/text_with_background/'),
        ),
    ]
