# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0014_abouttextwithbackground_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_aboutimage', serialize=False, to='cms.CMSPlugin')),
                ('image', models.ImageField(null=True, upload_to='about/plugins/image/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
