# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0016_aboutfeatures_aboutfeaturesitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTitleAccentWithImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_abouttitleaccentwithimage', serialize=False, to='cms.CMSPlugin')),
                ('text_before_title', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('text_after_title', models.TextField(max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='about/plugins/title_accent_with_image/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
