# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aboutcolumnswithbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcolumnswithbackground',
            name='image',
            field=models.ImageField(null=True, upload_to='about/plugins/columns_with_background/'),
        ),
    ]
