# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-13 13:23
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_aboutcolumns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcolumns',
            name='left_column_text',
            field=djangocms_text_ckeditor.fields.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutcolumns',
            name='right_column_text',
            field=djangocms_text_ckeditor.fields.HTMLField(),
        ),
    ]
