# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-13 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_aboutframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoptextcylinder',
            old_name='text',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='shoptextwaves',
            old_name='text',
            new_name='label',
        ),
    ]
