# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-14 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190613_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouttextwaves',
            name='label',
        ),
        migrations.RemoveField(
            model_name='shoptextcylinder',
            name='label',
        ),
        migrations.RemoveField(
            model_name='shoptextwaves',
            name='label',
        ),
    ]
