# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-16 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0025_auto_20190614_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_decoration', serialize=False, to='cms.CMSPlugin')),
                ('offset_top', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('offset_bottom', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('variant', models.CharField(choices=[('bird', 'Bird with radio'), ('disc', 'Record with cover')], default='bird', max_length=7)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
