# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-16 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_decoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='offset_top',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
    ]
