# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-16 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190616_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='variant',
            field=models.CharField(choices=[('bird', 'Bird with radio'), ('disk', 'Record with cover')], default='bird', max_length=7),
        ),
    ]
