# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-01 11:31
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190616_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptextandframe',
            name='frame_text',
            field=djangocms_text_ckeditor.fields.HTMLField(),
        ),
    ]
