# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-05 16:15
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Separator',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_separator', serialize=False, to='cms.CMSPlugin')),
                ('size', apps.core.fields.IntegerRangeField(default=1, verbose_name='Толщина линии')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Особый цвет линии (#HEX/RGB/RGBA)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Spacer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_spacer', serialize=False, to='cms.CMSPlugin')),
                ('height', apps.core.fields.IntegerRangeField(default=0, verbose_name='Отступ')),
                ('height_mobile', apps.core.fields.IntegerRangeField(blank=True, null=True, verbose_name='Особый отступ для мобильных устройств (необязательно)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='pluginseparator',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='pluginspacer',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='PluginSeparator',
        ),
        migrations.DeleteModel(
            name='PluginSpacer',
        ),
    ]
