# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-31 07:22
from __future__ import unicode_literals

import apps.core.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0002_auto_20200205_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_ticker', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=1024)),
                ('speed', apps.core.fields.IntegerRangeField(default=100, verbose_name='Скорость')),
                ('href', models.CharField(blank=True, max_length=1024, null=True)),
                ('color', colorfield.fields.ColorField(blank=True, max_length=18, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='separator',
            name='color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Особый цвет линии (#HEX/RGB/RGBA)'),
        ),
    ]
