# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-31 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common', '0002_auto_20200204_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textckeditor',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='TextCKEditor',
        ),
    ]
